[nix]
version = "2"

[[packages]]
name = "python38"
version = "3.8.0"
system = "x86_64-linux"

[[packages]]
name = "libgl1"
version = "1.3.1-1"
system = "x86_64-linux"
source = "http://archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libgl1_1.3.1-1_amd64.deb"

[[packages]]
name = "libglx0"
version = "1.3.1-1"
system = "x86_64-linux"
source = "http://archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libglx0_1.3.1-1_amd64.deb"

[[packages]]
name = "libglvnd0"
version = "1.3.1-1"
system = "x86_64-linux"
source = "http://archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libglvnd0_1.3.1-1_amd64.deb"

[[packages]]
name = "libc6"
version = "2.31-0ubuntu9"
system = "x86_64-linux"
source = "http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9_amd64.deb"
