[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "cd ./server && gunicorn djangoBackend.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
