[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "gunicorn djangoBackend.wsgi --bind=8000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
